### PR TITLE
Update autorunBL to version 1.3

### PR DESCRIPTION
**Pull request by VonSzarvas**
1. Update autorunBL to version 1.3
2. Rebuilt with latest SimpleLibraries for BlocklyProp
3. libwifi fix for P0 included with autorunBL src. The libwifi folder 
will be updated into SimpleLibraries master in the near future and then 
will not be required here if building from src.
4. oled_asmfast.c src included, is optimized and minimized for BadgeWX
5. fsimage.bin in release/core updated to include the new autorunBL 
file.

### CODE REVIEW

**Comment by PropGit** [comment]
@VonSzarvas - Wow, there are a ton of changes in BadgeWX-Bootloader.c.  I don't understand them all, but looks like mostly cleanup from previous dev.

Question: oled_asmfast.c  -  Will that stay with this project now (even after libwifi is removed when SimpleLibraries are updated)?  And is it built into autorunBL.bin when compiled?

**Comment by VonSzarvas** [comment]
cleanup and some optimizing to fit in stack.oled_asmfast.c.   yes will stay. not connected to libwifi issue.this oled version is smaller with reduced features suitable for Badge available bootloader space. And uses opendrain reset, instead of push-pull.autorunBL.bin includes this oled version, and the sources include it too, for future rebuilds. So, yes, to your Q.Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Parallax Git Administrator <notifications@github.com> Date: 23/05/2019  21:32  (GMT+01:00) To: parallaxinc/BadgeWX <BadgeWX@noreply.github.com> Cc: Michael <vonszarvas@atomitech.hu>, Mention <mention@noreply.github.com> Subject: Re: [parallaxinc/BadgeWX] Update autorunBL to version 1.3 (#8) @VonSzarvas - Wow, there are a ton of changes in BadgeWX-Bootloader.c.  I don't understand them all, but looks like mostly cleanup from previous dev.
Question: oled_asmfast.c  -  Will that stay with this project now (even after libwifi is removed when SimpleLibraries are updated)?  And is it built into autorunBL.bin when compiled?

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/parallaxinc/BadgeWX/pull/8?email_source=notifications\u0026email_token=ACYYYVRDVX6FCJXTZO5WVPDPW3WL3A5CNFSM4HNDSKQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWDIFCQ#issuecomment-495354506",
"url": "https://github.com/parallaxinc/BadgeWX/pull/8?email_source=notifications\u0026email_token=ACYYYVRDVX6FCJXTZO5WVPDPW3WL3A5CNFSM4HNDSKQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWDIFCQ#issuecomment-495354506",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by PropGit** [comment]
@VonSzarvas - Thanks.

Problems found.

This PR includes 104 files/changes, many of which are auto-generated binaries in libwifi folder from SimpleIDE that we don't like to fill up repositories with.  Also, there are many static binaries that were included from libwifi folder but could/should be Git LFS-managed.  I realize those are not Git LFS managed in Simple Libraries, but that repo was started before Git LFS was available.

Please redo and submit a new PR using the following techniques.  I'll leave this PR open until new PR resolves all this.

_NOTE: I started writing out these steps thinking this was easy, and now I see it's pretty involved.  If you'd like, I'll do this from my side and you can just reset your side and pull the updates... just let me know if that's what you'd prefer._

Steps:
I'm assuming your local master branch is still exactly as it is in this PR.
- Uncommit tip of master
```git reset --soft HEAD~```
- Unstage changes (leftover from uncommit above)
```git reset```
This will leave your local folder with the file/folder modifications you made from that last commit, but will completely remove the commit from your local repository logs and undoes the "add" of those changes to the local repository staging area
- Add the following to the bottom of the .gitignore file to exclude these files from future libwifi folder commits in this repo
```
#Temporary libwifi exclusions
Source/Boot/autorunBL/libwifi/cmm/
Source/Boot/autorunBL/libwifi/*.binary
Source/Boot/autorunBL/libwifi/*.elf
```
This should eliminate about 24 autobuilt files from the repo upon the next add, which we'll do later
- Modify the .gitattributes files to make all .gif, .png, .jpg files (wherever they are) managed by GIT LFS instead of included raw in the repository.
Change these three lines:
```
Source/Examples/*.gif filter=lfs diff=lfs merge=lfs -text
Source/Examples/*.png filter=lfs diff=lfs merge=lfs -text
Source/Examples/*.jpg filter=lfs diff=lfs merge=lfs -text
```
To be this instead:
```
*.gif filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text
```
- Add all changes
```git add --all```
- Check status to review file set
```git status```
There should be no .o, .binary, .elf files listed
- Check lfs status to look for GIT and LFS managed files
```git lfs status```
All files should be managed by Git (shown as "(Git:...)") except for .bin, and .png in this case (shown as "(LFS:....)").
- Commit the changes with a message of your choice
```git commit -m "your message here"```
- Force push over your repo fork's master
```git push --force origin master```
This is assuming "origin" is the nickname of your VonSzarvas fork.

**Comment by VonSzarvas** [comment]
before we start all that... how about we wait for libwifi to be updated in simplelibs master? then most these steps are not needed, plus we rebuild autorunBL without overrides. Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Parallax Git Administrator <notifications@github.com> Date: 23/05/2019  23:22  (GMT+01:00) To: parallaxinc/BadgeWX <BadgeWX@noreply.github.com> Cc: Michael <vonszarvas@atomitech.hu>, Mention <mention@noreply.github.com> Subject: Re: [parallaxinc/BadgeWX] Update autorunBL to version 1.3 (#8) @VonSzarvas - Thanks.
Problems found.
This PR includes 104 files/changes, many of which are auto-generated binaries in libwifi folder from SimpleIDE that we don't like to fill up repositories with.  Also, there are many static binaries that were included from libwifi folder but are could/should be Git LFS-managed.  I realize those are not Git LFS managed in Simple Libraries, but that repo was started but Git LFS was enabled.
Please redo and submit a new PR using the following techniques.  I'll leave this PR open until new PR resolves all this.
NOTE: I started writing out these steps thinking this was easy, and now I see it's pretty involved.  If you'd like, I'll do this from my side and you can just reset your side and pull the updates... just let me know if that's what you'd prefer.
Steps:
I'm assuming your local master branch is still exactly as it is in this PR.

Uncommit tip of master
git reset --soft HEAD~
Unstage changes (leftover from uncommit above)
git reset
This will leave your local folder with the file/folder modifications you made from that last commit, but will completely remove the commit from your local repository logs and undoes the "add" of those changes to the local repository staging area
Add the following to the bottom of the .gitignore file to exclude these files from future libwifi folder commits in this repo

#Temporary libwifi exclusions
Source/Boot/autorunBL/libwifi/cmm/
Source/Boot/autorunBL/libwifi/*.binary
Source/Boot/autorunBL/libwifi/*.elf

This should eliminate about 24 autobuilt files from the repo upon the next add, which we'll do later

Modify the .gitattributes files to make all .gif, .png, .jpg files (wherever they are) managed by GIT LFS instead of included raw in the repository.
Change these three lines:

Source/Examples/*.gif filter=lfs diff=lfs merge=lfs -text
Source/Examples/*.png filter=lfs diff=lfs merge=lfs -text
Source/Examples/*.jpg filter=lfs diff=lfs merge=lfs -text

To be this instead:
*.gif filter=lfs diff=lfs merge=lfs -text
*.png filter=lfs diff=lfs merge=lfs -text
*.jpg filter=lfs diff=lfs merge=lfs -text


Add all changes
git add --all
Check status to review file set
git status
There should be no .o, .binary, .elf files listed
Check lfs status to look for GIT and LFS managed files
git lfs status
Commit the changes with a message of your choice

- Force push over your repo fork's master
```git push --force origin master```




—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/parallaxinc/BadgeWX/pull/8?email_source=notifications\u0026email_token=ACYYYVT3NUEH4B3TRR66Z6LPW4DKPA5CNFSM4HNDSKQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWDQ3GA#issuecomment-495390104",
"url": "https://github.com/parallaxinc/BadgeWX/pull/8?email_source=notifications\u0026email_token=ACYYYVT3NUEH4B3TRR66Z6LPW4DKPA5CNFSM4HNDSKQ2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODWDQ3GA#issuecomment-495390104",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by VonSzarvas** [comment]
Task completed and new PR opened.

**Comment by PropGit** [comment]
I'm not sure how soon libwifi update can be applied to master in SimpleLibraries (there's some complications currently in how we're releasing updates there), but since you were successful with the instructions (as it appears) I'll merge this in now.

**Comment by VonSzarvas** [comment]
Perfect. Thank you.

**Pull request merged**
